Cumulate all allow rules with assertions
laminas/laminas-permissions-acl pull request #23
Opened 2021-10-05 03:01 UTC by PowerKiKi

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | yes
| New Feature   | no
| RFC           | no
| QA            | no

### Description

This fixes the regression introduced in 624567fe376a70e0bfb5aa8217d5afa13b9d6e61 (2.7.2),
where rules with assertions were no longer cumulated, but instead the process was
aborted on first failed assertion and the privilege was incorrectly denied.

That regression directly contradicted that official documentation that states:

> a failed assertion results in the rule not applying, and other
> rules would be used to determine whether access is allowed or denied.

That regression prevented to fallback on more generic rules. And it also made it very brittle
to work with role inheritance since the order of inheritance declaration became critically important,
while adding/removing privileges anywhere in the inheritance chain could incorrectly have side effect
for other roles in an unexpected way.

So this patch is essentially a revert of the problematic commit. And the use-case at the origin of the
regression is now solved, and tested, differently, with proper usage of (pre-)existing behavior, as it
should have been from the beginning.

So instead of the incorrect:

```php
$acl = new Acl();

$assertAllow = new TestAsset\ChildBooleanAssertion(true);
$assertDeny  = new TestAsset\ChildBooleanAssertion(false);

$acl->addRole('staff');
$acl->addResource('base');
$acl->allow('staff', 'base', 'update', $assertAllow);

$acl->addResource('user', 'base');
$acl->allow('staff', 'user', 'update', $assertDeny);
```

It should be:

```php
$acl = new Acl();
$assertAllow = new MockAssertion(true);

$acl->addRole('staff');
$acl->addResource('base');
$acl->allow('staff', 'base', 'update', $assertAllow);

$acl->addResource('user', 'base');
$acl->deny('staff', 'user', 'update', $assertAllow);
```

2021-10-05 03:03 UTC, PowerKiKi commented
This unfortunately is a BC break because the regression itself was a BC break. Though I'd say it should still be released as patch version since it mostly is a bugfix...

2021-10-11 01:53 UTC, PowerKiKi commented
@boesing, I am aware that you are not super familiar with this code base, but maybe you could still give it a "light" review and/or assign a reviewer to it ?

2021-11-08 05:44 UTC, PowerKiKi commented
@froschdesign would you be able to review this yourself, or alternatively recommend another reviewer, so that the PR does not get too old ?

2021-11-17 18:25 UTC, weierophinney requested changes, later dismissed
Overall, this looks good; I've just provided some suggestions to tighten it up.

2021-11-17 18:25 UTC, weierophinney commented on src/Acl.php
>          }
```suggestion
        if (null === $rule['assert'] || $assertionValue) {
            return $rule['type'];
        }
        
        if (null !== $resource || null !== $role || null !== $privilege) {
            return;
        }
        
        if (self::TYPE_ALLOW === $rule['type']) {
            return self::TYPE_DENY;
        }
```

There's no need for an `elseif` if you are returning from the block. Additionally, it makes it easier to identify the distinct exit conditions.

2021-11-17 18:25 UTC, weierophinney commented on test/AclTest.php
> +    public function testCanDenyAnInheritedRuleThatAllows()
```suggestion
    public function testCanDenyAnInheritedAllowRule()
```

As a native English speaker, I read this and thought "allows what?"; the suggested change makes it more clear that you are denying a previously set rule.

2021-11-18 00:30 UTC, PowerKiKi commented
Thank you for the review. I applied all your suggestions. IMHO this is now ready to be merged.

2021-12-03 04:33 UTC, PowerKiKi commented
@snapshotpl you attempted to rebase this PR a few hours ago. I did it for you. And since it has been reviewed by @weierophinney already, could you please considering merging it ?

2021-12-03 07:08 UTC, froschdesign commented
@PowerKiKi 
Your pull request will be released with [version 2.9.0](https://github.com/laminas/laminas-permissions-acl/milestone/6).

2021-12-03 08:48 UTC, Ocramius commented
Removing the `BC Break` label, since:

 1. we decided this is suited for a minor release
 2. it's actually fixing a BC Break (label would be confusing in release notes)

2021-12-03 08:49 UTC, Ocramius approved these changes
:ship:

2021-12-03 08:49 UTC, merged